version: "3.9"

services:
  db:
    image: timescale/timescaledb-ha:pg17
    environment:
      POSTGRES_PASSWORD: foobar
    ports:
      - "5433:5432"
    volumes:
      - data:/home/postgres/pgdata/data
volumes:
  data:
