version: "3.9"

services:
  db:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: foobar
    ports:
      - "5433:5432"
    volumes:
      - data:/home/postgres/pgdata/data
volumes:
  data:
