name: Build and Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Archive the build files
        run: zip -r recycler-app-api.zip . -x "*.git*" "*.github*" "*.pytest_cache*" "*.venv*" "*.idea*" "*.vscode*" "__pycache__/*" "*.pytest_cache/*" "*.mypy_cache/*" "*.coverage*"

      - name: Install AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-central-1

      - name: Deploy to Elastic Beanstalk
        run: |
          aws s3 cp recycler-app-api.zip s3://recycler-app/recycler-app-api-${{ github.sha }}.zip
          aws elasticbeanstalk create-application-version --application-name recycler-app-api --version-label ${{ github.sha }} --source-bundle S3Bucket=recycler-app,S3Key=recycler-app-api-${{ github.sha }}.zip
          aws elasticbeanstalk update-environment --application-name recycler-app-api --environment-name recyler-api-env --version-label ${{ github.sha }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Clean up
        run: rm recycler-app-api.zip
