name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3        

      - name: Build and push Docker image
        run: |
          docker compose -f docker-compose.yml build
          docker tag recycler-api:latest ${{ steps.login-ecr.outputs.registry }}/recycler-api
          docker push ${{ steps.login-ecr.outputs.registry }}/recycler-api

      - name: Deploy to Elastic Beanstalk
        run: |
          pip install awsebcli
          eb init -p docker recycler-app --region $AWS_REGION
          eb use recycler-app-env
          eb deploy
